# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='toDoListData',
            new_name='toDoPost',
        ),
    ]
