# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20161119_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gender', models.BooleanField(verbose_name='Gender:')),
                ('Pulse', models.CharField(max_length=10)),
                ('BloodP', models.CharField(max_length=10)),
                ('RespirationR', models.CharField(max_length=10)),
                ('Height', models.CharField(max_length=10)),
                ('Weight', models.CharField(max_length=10)),
                ('BMI', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=15, verbose_name='Age:')),
                ('Pallor', models.BooleanField(verbose_name='Pallor:')),
                ('Icterus', models.BooleanField(verbose_name='Icterus:')),
                ('Cyanosis', models.BooleanField(verbose_name='Cyanosis:')),
                ('Lymphadenopathy', models.BooleanField(verbose_name='Lymphadenopathy:')),
                ('ThyroidE', models.BooleanField(verbose_name='Thyroid Enlargement:')),
                ('PeripheralP', models.BooleanField(verbose_name='Peripheral Pulse:')),
                ('Csign', models.BooleanField(verbose_name='C sign:')),
                ('Tsign', models.BooleanField(verbose_name='T sign:')),
                ('Petechiae', models.BooleanField(verbose_name='Petechiae:')),
                ('Purpura', models.BooleanField(verbose_name='Purpura:')),
                ('Acanthosis', models.BooleanField(verbose_name='Acanthosis:')),
                ('SkinTags', models.BooleanField(verbose_name='Skin Tags:')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
        ),
    ]
