# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20161121_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseId',
        ),
    ]
