# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20161121_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='age',
        ),
        migrations.AddField(
            model_name='case',
            name='Age',
            field=models.CharField(default=-6, max_length=20, verbose_name='Age:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='Clubbing',
            field=models.BooleanField(default=1, verbose_name='Clubbing:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='BMI',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='BloodP',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='Height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='Pulse',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='RespirationR',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='Weight',
            field=models.CharField(max_length=20),
        ),
    ]
