# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20161121_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Acanthosis',
            field=models.BooleanField(default=0, verbose_name='Acanthosis:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Clubbing',
            field=models.BooleanField(default=0, verbose_name='Clubbing:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Csign',
            field=models.BooleanField(default=0, verbose_name='C sign:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Cyanosis',
            field=models.BooleanField(default=0, verbose_name='Cyanosis:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Gender',
            field=models.BooleanField(default=1, verbose_name='Gender:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Icterus',
            field=models.BooleanField(default=0, verbose_name='Icterus:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Lymphadenopathy',
            field=models.BooleanField(default=0, verbose_name='Lymphadenopathy:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Pallor',
            field=models.BooleanField(default=0, verbose_name='Pallor:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='PeripheralP',
            field=models.BooleanField(default=0, verbose_name='Peripheral Pulse:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Petechiae',
            field=models.BooleanField(default=0, verbose_name='Petechiae:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Purpura',
            field=models.BooleanField(default=0, verbose_name='Purpura:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='SkinTags',
            field=models.BooleanField(default=0, verbose_name='Skin Tags:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='ThyroidE',
            field=models.BooleanField(default=0, verbose_name='Thyroid Enlargement:'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Tsign',
            field=models.BooleanField(default=0, verbose_name='T sign:'),
        ),
    ]
