# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20161121_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='doc',
        ),
        migrations.AlterField(
            model_name='case',
            name='patientob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
        ),
    ]
