# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20161125_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='patientob',
        ),
    ]
