# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20161208_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='HeightUnits',
        ),
        migrations.RemoveField(
            model_name='case',
            name='WeightUnits',
        ),
    ]
