# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20161208_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Age', models.CharField(max_length=20, verbose_name='Age:')),
                ('Gender', models.BooleanField(default=1, verbose_name='Gender:')),
                ('Pulse', models.CharField(max_length=20)),
                ('BloodP', models.CharField(max_length=20)),
                ('RespirationR', models.CharField(max_length=20)),
                ('Height', models.CharField(max_length=20)),
                ('HeightUnits', models.CharField(default='cm', max_length=20)),
                ('Weight', models.CharField(max_length=20)),
                ('WeightUnits', models.CharField(default='kg', max_length=20)),
                ('BMI', models.CharField(max_length=20)),
                ('Pallor', models.BooleanField(default=0, verbose_name='Pallor:')),
                ('Icterus', models.BooleanField(default=0, verbose_name='Icterus:')),
                ('Cyanosis', models.BooleanField(default=0, verbose_name='Cyanosis:')),
                ('Clubbing', models.BooleanField(default=0, verbose_name='Clubbing:')),
                ('Lymphadenopathy', models.BooleanField(default=0, verbose_name='Lymphadenopathy:')),
                ('ThyroidE', models.BooleanField(default=0, verbose_name='Thyroid Enlargement:')),
                ('PeripheralP', models.BooleanField(default=0, verbose_name='Peripheral Pulse:')),
                ('Csign', models.BooleanField(default=0, verbose_name='C sign:')),
                ('Tsign', models.BooleanField(default=0, verbose_name='T sign:')),
                ('Petechiae', models.BooleanField(default=0, verbose_name='Petechiae:')),
                ('Purpura', models.BooleanField(default=0, verbose_name='Purpura:')),
                ('Acanthosis', models.BooleanField(default=0, verbose_name='Acanthosis:')),
                ('SkinTags', models.BooleanField(default=0, verbose_name='Skin Tags:')),
                ('patientob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
    ]
